// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (typeof window !== 'undefined' && localStorage.getItem('selenium-mock-auth') === 'true') {
      if (prop === 'auth') {
        return {
          onAuthStateChange(cb: any) {
            const token = localStorage.getItem("sb-apestyiapotoonphzpzu-auth-token");
            if (token) {
              try {
                const session = JSON.parse(token);
                setTimeout(() => cb("SIGNED_IN", session), 0);
              } catch (e) {}
            }
            return { data: { subscription: { unsubscribe: () => {} } } };
          },
          async getSession() {
            const token = localStorage.getItem("sb-apestyiapotoonphzpzu-auth-token");
            if (token) {
              try {
                const session = JSON.parse(token);
                return { data: { session } };
              } catch (e) {}
            }
            return { data: { session: null } };
          },
          async signInWithPassword({ email, password }: any) {
            if (email === "test@example.com" && password === "password123") {
              const session = {
                access_token: "mock-token",
                user: { id: "mock-user-id", email: "test@example.com" }
              };
              localStorage.setItem("sb-apestyiapotoonphzpzu-auth-token", JSON.stringify(session));
              setTimeout(() => {
                window.location.href = "#/dashboard";
              }, 100);
              return { data: { session }, error: null };
            }
            return { data: { session: null }, error: { message: "Invalid login credentials" } };
          },
          async getUser() {
            const token = localStorage.getItem("sb-apestyiapotoonphzpzu-auth-token");
            if (token) {
              try {
                const session = JSON.parse(token);
                return { data: { user: session.user } };
              } catch (e) {}
            }
            return { data: { user: null } };
          },
          async signOut() {
            localStorage.removeItem("sb-apestyiapotoonphzpzu-auth-token");
            window.location.href = "#/auth";
            return { error: null };
          }
        };
      }
      if (prop === 'from') {
        return (table: string) => {
          const chain = {
            select(cols?: string) { return chain; },
            order(col: string, opts?: any) { return chain; },
            eq(col: string, val: any) { return chain; },
            limit(l: number) { return chain; },
            maybeSingle() {
              if (table === "profiles") {
                return Promise.resolve({ data: { display_name: "Mock User", night_mode_safety: true, avoid_isolated: true, prefer_crowded: true }, error: null });
              }
              return Promise.resolve({ data: null, error: null });
            },
            async then(onfulfilled: any) {
              if (table === "saved_routes") {
                return onfulfilled({ data: [], error: null });
              }
              if (table === "profiles") {
                return onfulfilled({ data: { display_name: "Mock User", night_mode_safety: true, avoid_isolated: true, prefer_crowded: true }, error: null });
              }
              if (table === "incident_reports") {
                return onfulfilled({ data: [], error: null });
              }
              return onfulfilled({ data: null, error: null });
            },
            delete() { return chain; },
            update(val: any) { return chain; }
          };
          return chain;
        };
      }
    }
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

